name: Build Firmware

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev

      - name: Build firmware
        run: make all

      - name: Upload artifacts
        run: |
          FIRMWARELIST="900 903 950 900 1000 1050 1100"
          for fw in $FIRMWARELIST; do
            echo "Uploading artifact for firmware $fw"
            gh action upload-artifact --name firmware-$fw --path build/$fw/
          done